<!DOCTYPE html>
<html lang="it"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-eec68b17241c1efd3eae2de50d816e3e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Cristiano De Michele">
  <title>Programmazione Scientifica++ – Programmazione Scientifica++: Lezione 2</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #383a42;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #383a42; } /* Normal */
    code span.al { color: #95da4c; background-color: #4d1f24; font-weight: bold; } /* Alert */
    code span.an { color: #50a14f; } /* Annotation */
    code span.at { color: #a626a4; } /* Attribute */
    code span.bn { color: #986801; } /* BaseN */
    code span.bu { color: #a626a4; } /* BuiltIn */
    code span.cf { color: #a626a4; } /* ControlFlow */
    code span.ch { color: #50a14f; } /* Char */
    code span.cn { color: #986801; } /* Constant */
    code span.co { color: #a0a1a7; font-style: italic; } /* Comment */
    code span.cv { color: #e45649; font-style: italic; } /* CommentVar */
    code span.do { color: #e45649; } /* Documentation */
    code span.dt { color: #a626a4; } /* DataType */
    code span.dv { color: #986801; } /* DecVal */
    code span.er { color: #f44747; text-decoration: underline; } /* Error */
    code span.ex { color: #4078f2; font-weight: bold; } /* Extension */
    code span.fl { color: #986801; } /* Float */
    code span.fu { color: #4078f2; } /* Function */
    code span.im { color: #50a14f; } /* Import */
    code span.in { color: #c45b00; } /* Information */
    code span.kw { color: #a626a4; } /* Keyword */
    code span.op { color: #a626a4; } /* Operator */
    code span.ot { color: #27ae60; } /* Other */
    code span.pp { color: #a626a4; } /* Preprocessor */
    code span.re { color: #2980b9; background-color: #153042; } /* RegionMarker */
    code span.sc { color: #0184bc; } /* SpecialChar */
    code span.ss { color: #da4453; } /* SpecialString */
    code span.st { color: #50a14f; } /* String */
    code span.va { color: #e45649; } /* Variable */
    code span.vs { color: #da4453; } /* VerbatimString */
    code span.wa { color: #da4453; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="../annotazioni.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script>
  // Collega ogni spiegazione alla sua riga di codice e viceversa.
  //   - col mouse: passandoci sopra si accendono entrambe;
  //   - col dito (tablet): un tocco FISSA l'evidenziazione, un altro tocco
  //     (o il tocco su un'altra annotazione) la sposta.
  // Va usato con "code-annotations: below", che lascia le spiegazioni visibili.
  window.addEventListener('load', function () {
    function righe(spec) {                 // "2" | "2,4" | "2-4"
      var out = [];
      String(spec || '').split(',').forEach(function (p) {
        var m = p.trim().match(/^(\d+)(?:-(\d+))?$/);
        if (!m) return;
        for (var i = +m[1], b = m[2] ? +m[2] : +m[1]; i <= b; i++) out.push(i);
      });
      return out;
    }

    var fissato = null;                    // gruppo attualmente bloccato dal tocco

    document.querySelectorAll('.code-annotation-container-grid').forEach(function (dl) {
      var dts = dl.querySelectorAll('dt');
      dl.querySelectorAll('dd > span[data-code-annotation]').forEach(function (span, i) {
        var cella = span.dataset.codeCell, n = span.dataset.codeAnnotation;
        var gruppo = [span, span.parentElement, dts[i]].filter(Boolean);

        var anchor = document.querySelector(
          '.code-annotation-anchor[data-target-cell="' + cella + '"][data-target-annotation="' + n + '"]');
        if (anchor) gruppo.push(anchor);

        righe(span.dataset.codeLines).forEach(function (r) {
          var el = document.getElementById(cella + '-' + r);
          if (el) gruppo.push(el);
        });

        function on()  { gruppo.forEach(function (e) { e.classList.add('ann-on'); }); }
        function off() { gruppo.forEach(function (e) { e.classList.remove('ann-on'); }); }

        var trigger = [span.parentElement, dts[i], anchor].filter(Boolean);
        trigger.forEach(function (t) {
          t.addEventListener('mouseenter', function () { if (!fissato) on(); });
          t.addEventListener('mouseleave', function () { if (fissato !== gruppo) off(); });
          t.addEventListener('click', function (ev) {
            ev.preventDefault(); ev.stopPropagation();
            if (fissato === gruppo) { off(); fissato = null; return; }
            if (fissato) fissato.forEach(function (e) { e.classList.remove('ann-on'); });
            on(); fissato = gruppo;
          });
        });
      });
    });
  });
  </script>
  <style>
  /* pulsanti "gomma" e "schermo intero" accanto a lavagna e notes canvas (29/9/2026) */
  .reveal .slide-chalkboard-buttons .fa-eraser::before{background-image:url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(42, 118, 221)" viewBox="0 0 16 16"><path d="M8.086 2.207a2 2 0 0 1 2.828 0l3.879 3.879a2 2 0 0 1 0 2.828l-5.5 5.5A2 2 0 0 1 7.879 15H5.12a2 2 0 0 1-1.414-.586l-2.5-2.5a2 2 0 0 1 0-2.828l6.879-6.879zm2.121.707a1 1 0 0 0-1.414 0L4.16 7.547l5.293 5.293 4.633-4.633a1 1 0 0 0 0-1.414l-3.879-3.879zM8.746 13.547 3.453 8.254 1.914 9.793a1 1 0 0 0 0 1.414l2.5 2.5a1 1 0 0 0 .707.293H7.88a1 1 0 0 0 .707-.293l.16-.16z"/></svg>')}
  .reveal .slide-chalkboard-buttons .fa-schermo-intero::before{background-image:url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(42, 118, 221)" viewBox="0 0 16 16"><path d="M1.5 1a.5.5 0 0 0-.5.5v4a.5.5 0 0 1-1 0v-4A1.5 1.5 0 0 1 1.5 0h4a.5.5 0 0 1 0 1h-4zM10 .5a.5.5 0 0 1 .5-.5h4A1.5 1.5 0 0 1 16 1.5v4a.5.5 0 0 1-1 0v-4a.5.5 0 0 0-.5-.5h-4a.5.5 0 0 1-.5-.5zM.5 10a.5.5 0 0 1 .5.5v4a.5.5 0 0 0 .5.5h4a.5.5 0 0 1 0 1h-4A1.5 1.5 0 0 1 0 14.5v-4a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v4a1.5 1.5 0 0 1-1.5 1.5h-4a.5.5 0 0 1 0-1h4a.5.5 0 0 0 .5-.5v-4a.5.5 0 0 1 .5-.5z"/></svg>')}
  .reveal .slide-chalkboard-buttons .fa-esci-schermo::before{background-image:url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(42, 118, 221)" viewBox="0 0 16 16"><path d="M5.5 0a.5.5 0 0 1 .5.5v4A1.5 1.5 0 0 1 4.5 6h-4a.5.5 0 0 1 0-1h4a.5.5 0 0 0 .5-.5v-4a.5.5 0 0 1 .5-.5zm5 0a.5.5 0 0 1 .5.5v4a.5.5 0 0 0 .5.5h4a.5.5 0 0 1 0 1h-4A1.5 1.5 0 0 1 10 4.5v-4a.5.5 0 0 1 .5-.5zM0 10.5a.5.5 0 0 1 .5-.5h4A1.5 1.5 0 0 1 6 11.5v4a.5.5 0 0 1-1 0v-4a.5.5 0 0 0-.5-.5h-4a.5.5 0 0 1-.5-.5zm10 1a1.5 1.5 0 0 1 1.5-1.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 0-.5.5v4a.5.5 0 0 1-1 0v-4z"/></svg>')}
  </style>
  <script>
  // Due pulsanti in piu' in basso a sinistra, per chi presenta dal tablet
  // senza tastiera:
  //  - la gomma cancella in un colpo i disegni della slide corrente, nel modo
  //    attivo (la lavagna se e' aperta, altrimenti il notes canvas): e' il
  //    tasto Canc. Le altre slide non si toccano;
  //  - schermo intero, entra ed esce (il tasto F); l'icona segue lo stato.
  window.addEventListener('load', function () {
    var tentativi = 0;
    (function aggiungi() {
      var div = document.querySelector('.reveal .slide-chalkboard-buttons');
      if (!div || typeof RevealChalkboard === 'undefined') {
        if (++tentativi < 50) setTimeout(aggiungi, 100);
        return;
      }
      if (div.querySelector('.fa-eraser')) return;
      var span = document.createElement('span');
      span.title = 'Cancella i disegni di questa slide (Canc)';
      var icona = document.createElement('i');
      icona.className = 'fas fa-eraser';
      span.appendChild(icona);
      span.onclick = function (ev) { ev.preventDefault(); RevealChalkboard.clear(); };
      div.appendChild(span);

      var doc = document.documentElement;
      if (!doc.requestFullscreen) return;       // browser senza schermo intero
      var fs = document.createElement('span');
      var ifs = document.createElement('i');
      fs.appendChild(ifs);
      function aggiorna() {
        var dentro = !!document.fullscreenElement;
        ifs.className = 'fas ' + (dentro ? 'fa-esci-schermo' : 'fa-schermo-intero');
        fs.title = dentro ? 'Esci dallo schermo intero (F)' : 'Schermo intero (F)';
      }
      fs.onclick = function (ev) {
        ev.preventDefault();
        if (document.fullscreenElement) document.exitFullscreen();
        else doc.requestFullscreen().catch(function () {});
      };
      document.addEventListener('fullscreenchange', aggiorna);
      aggiorna();
      div.appendChild(fs);
    })();
  });
  </script>
  <script>
  // Swipe a DUE dita per cambiare slide (29/9/2026). Lo swipe a un dito resta
  // quello di reveal.js, che pero' non funziona se il dito parte su qualcosa che
  // scorre (slide .scrollable, blocchi di codice): li' il browser si prende il
  // gesto per lo scorrimento. Con due dita si cambia slide ovunque, anche con la
  // matita attiva. Un pinch (dita che si allontanano) resta uno zoom.
  (function () {
    var SOGLIA = 60;            // px di spostamento del punto medio delle due dita
    var g = null;               // gesto a due dita in corso
    var tocchi = new Set();     // pointer "touch" attivi
    var muto = false;           // da quando posi il secondo dito a quando li togli tutti

    function medio(t) {
      return { x: (t[0].clientX + t[1].clientX) / 2, y: (t[0].clientY + t[1].clientY) / 2,
               d: Math.hypot(t[0].clientX - t[1].clientX, t[0].clientY - t[1].clientY) };
    }
    document.addEventListener('touchstart', function (e) {
      if (e.touches.length === 2) { var m = medio(e.touches); g = { x: m.x, y: m.y, d: m.d, fatto: false }; }
      else if (e.touches.length > 2) g = null;
    }, { capture: true, passive: true });

    document.addEventListener('touchmove', function (e) {
      if (e.touches.length < 2) return;
      e.stopPropagation();                      // la lavagna non disegna col secondo dito
      if (!g || e.touches.length !== 2) return;
      if (g.fatto) { if (e.cancelable) e.preventDefault(); return; }
      var m = medio(e.touches), dx = m.x - g.x, dy = m.y - g.y;
      if (Math.abs(m.d - g.d) > 0.35 * g.d) { g = null; return; }      // pinch: al browser
      if (Math.abs(dx) > SOGLIA && Math.abs(dx) > 1.5 * Math.abs(dy)) {
        g.fatto = true;
        if (e.cancelable) e.preventDefault();
        if (dx < 0) Reveal.next(); else Reveal.prev();
      } else if (Math.abs(dy) > SOGLIA && Math.abs(dy) > 1.5 * Math.abs(dx)) {
        g = null;                                // due dita in verticale: scorrimento
      }
    }, { capture: true, passive: false });

    document.addEventListener('touchend', function (e) {
      if (e.touches.length < 2) g = null;
    }, true);
    document.addEventListener('touchcancel', function (e) {
      if (e.touches.length < 2) g = null;
    }, true);

    // reveal.js legge lo swipe dai pointer events, dito per dito: con due dita
    // vedrebbe anche uno swipe a un dito e salterebbe due slide. Dal secondo dito
    // in poi, e finche' non si alzano tutti, i suoi pointermove non gli arrivano.
    function conta(e) {
      if (e.pointerType !== 'touch') return;
      if (e.type === 'pointerdown') { tocchi.add(e.pointerId); if (tocchi.size >= 2) muto = true; }
      else { tocchi.delete(e.pointerId); if (tocchi.size === 0) muto = false; }
    }
    ['pointerdown', 'pointerup', 'pointercancel'].forEach(function (t) {
      document.addEventListener(t, conta, true);
    });
    document.addEventListener('pointermove', function (e) {
      if (e.pointerType === 'touch' && muto) e.stopPropagation();
    }, true);
  })();
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Programmazione Scientifica++: Lezione 2</h1>
  <p class="subtitle">Deep Learning — Neurone, MLP e Vettorizzazione</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Cristiano De Michele
</div>
</div>
</div>

</section>
<section id="argomenti-di-oggi" class="slide level2 smaller">
<h2>Argomenti di Oggi</h2>
<ul>
<li>Il Neurone Biologico e Matematico</li>
<li>Il Problema della Linearità</li>
<li>Funzioni di Attivazione: gradino, sigmoide, ReLU</li>
<li>Multi-Layer Perceptron (MLP)</li>
<li>La Vettorizzazione e le Matrici</li>
</ul>
</section>
<section id="prima-del-c-la-matematica" class="slide level2 smaller">
<h2>Prima del C++: la Matematica</h2>
<p>In questa lezione non scriveremo una riga di C++, e non è un rinvio: prima di costruire un software bisogna sapere <strong>quali equazioni</strong> deve calcolare. Un programma robusto che calcola l’equazione sbagliata è un programma inutile.</p>
<p>Oggi e nella prossima lezione ci occupiamo della <strong>teoria matematica</strong> alla base del Machine Learning: scopriremo <em>cosa</em> dovrà calcolare ogni <code>Layer</code> del vostro framework, e <em>perché</em> l’algebra lineare vi salverà la vita.</p>
<p>Gli strumenti del C++ — oggetti, puntatori, polimorfismo, template, eccezioni — arrivano dalla Lezione 4 in poi, e li costruirete addosso a queste equazioni.</p>
</section>
<section id="il-neurone-biologico" class="slide level2 smaller">
<h2>Il Neurone Biologico</h2>
<p>Tutto parte dal cervello umano. Un neurone biologico riceve segnali chimico-elettrici da altri neuroni tramite diramazioni chiamate <strong>Dendriti</strong>.</p>
<p>Questi segnali non hanno tutti la stessa importanza. Alcuni eccitano il neurone, altri lo inibiscono. Se la somma complessiva dell’eccitazione supera una certa <em>Soglia</em>, il neurone “scatta” e spara a sua volta un impulso elettrico lungo il suo <strong>Assone</strong> verso i neuroni successivi.</p>
<p>Negli anni ’50, i matematici si chiesero: “Possiamo scriverlo sotto forma di equazione?”.</p>

<img data-src="images/neurone_biologico.png" class="quarto-figure quarto-figure-center r-stretch"><p><span style="font-size: 0.55em; color: #6b6b6b;">Figura da T. Rashid, <em>Make Your Own Neural Network</em>.</span></p>
</section>
<section id="neuroni-in-rete" class="slide level2 smaller">
<h2>Neuroni in rete</h2>

<img data-src="images/neuroni_in_rete.png" class="quarto-figure quarto-figure-center r-stretch"><p>Il segnale che esce dai terminali di un neurone entra nei dendriti di altri: un neurone da solo decide poco, <strong>una rete</strong> di neuroni collegati fa il lavoro vero. È l’idea che ritroveremo nel <em>Multi-Layer Perceptron</em>.</p>
<p><span style="font-size: 0.55em; color: #6b6b6b;">Figura da T. Rashid, <em>Make Your Own Neural Network</em>.</span></p>
</section>
<section id="il-modello-matematico-perceptron" class="slide level2 smaller">
<h2>Il Modello Matematico (Perceptron)</h2>
<p>L’unità fondamentale di una Rete Neurale Artificiale si chiama <strong>Percettrone</strong> — è il singolo neurone artificiale, quello che Rashid nel libro chiama semplicemente <em>neurone</em> o <em>nodo</em>: stessa cosa, nome storico (Rosenblatt, 1958). Prende una serie di input numerici <span class="math inline">\(x_i\)</span>, li moltiplica per dei “pesi” <span class="math inline">\(w_i\)</span> (che simulano l’importanza del collegamento biologico), e li somma tutti assieme.</p>
<p>L’equazione fondamentale del singolo neurone è:</p>
<p><span class="math display">\[ z = \sum_{i=1}^{n} (w_i \cdot x_i) + b \]</span></p>
<ul>
<li><span class="math inline">\(x_i\)</span>: Il segnale in ingresso.</li>
<li><span class="math inline">\(w_i\)</span>: Il Peso (Weight).</li>
<li><span class="math inline">\(b\)</span>: Il <strong>Bias</strong>, un numero che “sposta” artificialmente la soglia di scatto del neurone.</li>
</ul>
</section>
<section id="la-combinazione-lineare" class="slide level2 smaller">
<h2>La Combinazione Lineare</h2>
<p>Guardate bene l’equazione precedente. Non vi ricorda nulla?</p>
<p>Se prendiamo un neurone con un solo input <span class="math inline">\(x\)</span>, la sua equazione diventa: <span class="math display">\[ z = w \cdot x + b \]</span></p>
<p>Questa è l’equazione di una <strong>Retta</strong> (<span class="math inline">\(y = mx + q\)</span>). Il neurone artificiale di base non è nient’altro che una combinazione lineare dei suoi input. Crea un “piano” matematico che taglia lo spazio a metà.</p>
</section>
<section id="un-mondo-troppo-semplice-linearità" class="slide level2 smaller">
<h2>Un mondo troppo semplice (Linearità)</h2>
<p>Il neurone dice “sì” quando <span class="math inline">\(z &gt; 0\)</span> e “no” altrimenti: il confine fra le due risposte è <span class="math inline">\(z = 0\)</span>. Con un ingresso solo, se <span class="math inline">\(w \neq 0\)</span>, la retta <span class="math inline">\(z = w\,x + b\)</span> taglia lo zero in un punto: il confine è quel punto, una <strong>soglia</strong>. Con due ingressi il confine è una <strong>retta</strong> nel piano degli ingressi; con <span class="math inline">\(n\)</span> ingressi, un iperpiano.</p>
<p>Quindi un singolo neurone può risolvere solo problemi <strong>linearmente separabili</strong>: quelli per cui esiste un confine che lascia tutti i “sì” da una parte e tutti i “no” dall’altra.</p>
<p>Ma se i “sì” stanno in mezzo ai “no”? Una soglia sola non chiude una finestra, e una retta sola non racchiude né una fascia né un cerchio. Il percettrone fallisce.</p>
<p>Lo vediamo prima con un ingresso, poi con due.</p>
</section>
<section id="stessi-pazienti-due-domande" class="slide level2 smaller">
<h2>Stessi pazienti, due domande</h2>

<img data-src="images/glicemia_soglia_finestra.png" class="quarto-figure quarto-figure-center r-stretch"><p>Un solo ingresso, la glicemia a digiuno, e due domande. «Diabete?», cioè un valore da 126 mg/dL in su, è una soglia: il problema è linearmente separabile. «Glicemia nella norma?» ha i sì in mezzo, perché la glicemia è un problema sia troppo bassa sia troppo alta: è una finestra, nessuna soglia sola la chiude, e il problema non è linearmente separabile. Stessi pazienti, stessi numeri: a decidere è <strong>la domanda</strong>.</p>
<aside class="notes">
<p>Soglie ADA (Standards of Care), glicemia a digiuno: da 126 mg/dL in su è il criterio del diabete (la diagnosi vera chiede due risultati anomali, fra glicemia ripetuta, emoglobina glicata e carico orale, salvo iperglicemia evidente); 100–125 è alterata glicemia a digiuno. 70 è la soglia ADA di allerta per l’ipoglicemia (livello 1: 54–69; livello 2: sotto 54), definita per chi ha il diabete; l’intervallo 70–99 come «norma» è quello usuale dei laboratori. Qui conta la forma del problema, non la clinica. I pazienti della figura sono inventati. Il punto da far passare: la separabilità lineare non dipende dai soli dati, dipende dalle etichette. Con due ingressi succede lo stesso ai quattro vertici del quadrato: AND e OR sì, XOR no (slide «AND e OR: la retta esiste» e «Il Problema dello XOR»).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="coccinelle-e-bruchi" class="slide level2 smaller">
<h2>Coccinelle e bruchi</h2>
<div class="columns">
<div class="column" style="width:54%;">
<p>È l’esempio di classificazione del libro di Rashid. Di due tipi di insetti misuriamo la larghezza <span class="math inline">\(x_1\)</span> e la lunghezza <span class="math inline">\(x_2\)</span> (qui le misure sono inventate): le coccinelle sono larghe e corte, i bruchi stretti e lunghi.</p>
<p>Nella «Combinazione Lineare» la retta dava <span class="math inline">\(z\)</span> in funzione di <span class="math inline">\(x\)</span>. Qui, con due ingressi, la retta <span class="math inline">\(x_2 = x_1\)</span> non calcola un numero da un altro: <strong>divide il piano in due</strong>, i bruchi sopra e le coccinelle sotto.</p>
<p>Come neurone: <span class="math inline">\(z = x_2 - x_1\)</span>, cioè pesi <span class="math inline">\(-1\)</span> e <span class="math inline">\(1\)</span> e bias <span class="math inline">\(0\)</span>. «Bruco?» vale sì quando <span class="math inline">\(z &gt; 0\)</span>: quando l’insetto è più lungo che largo.</p>
</div><div class="column" style="width:46%;">
<p><img data-src="images/coccinelle_bruchi.png"></p>
</div></div>
<aside class="notes">
<p>Nel libro (capitoli «Classifying is Not Very Different from Predicting» e «Training A Simple Classifier») la retta è <span class="math inline">\(y = Ax\)</span> e la pendenza <span class="math inline">\(A\)</span> si impara da due esempi, coccinella <span class="math inline">\((3.0, 1.0)\)</span> e bruco <span class="math inline">\((1.0, 3.0)\)</span>, con learning rate <span class="math inline">\(L = 0.5\)</span>: <span class="math inline">\(A\)</span> va da <span class="math inline">\(0.25\)</span> a <span class="math inline">\(0.3083\)</span> e poi a <span class="math inline">\(0.6042\)</span>. Qui gli ingressi sono <span class="math inline">\(x_1, x_2\)</span> e non <span class="math inline">\(x, y\)</span> (nel corso <span class="math inline">\(y\)</span> è l’uscita), e la pendenza vale <span class="math inline">\(1\)</span> invece di chiamarsi <span class="math inline">\(A\)</span> (<span class="math inline">\(A\)</span> è un ingresso nelle slide delle porte logiche). Attenzione al libro: nel PDF in BIBLIO il secondo passo con <span class="math inline">\(L = 0.5\)</span> usa per il bruco l’obiettivo <span class="math inline">\(0.9\)</span> (e la figura disegna <span class="math inline">\(y = 0.6042\,x\)</span>), mentre poco prima, per lo stesso bruco, era <span class="math inline">\(2.9\)</span>; con <span class="math inline">\(2.9\)</span> verrebbe <span class="math inline">\(A = 1.6042\)</span>. Altre stampe potrebbero avere già la correzione. Le due rette separano comunque i due esempi. Misure della figura inventate. Con questi dati separa qualunque retta per l’origine con pendenza fra <span class="math inline">\(0.574\)</span> e <span class="math inline">\(2.214\)</span>: sia <span class="math inline">\(0.6042\)</span> sia <span class="math inline">\(1.6042\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="coccinelle-cimici-e-bruchi" class="slide level2 smaller">
<h2>Coccinelle, cimici e bruchi</h2>
<div class="columns">
<div class="column" style="width:54%;">
<p>Aggiungiamo un terzo insetto, la <strong>cimice</strong>: più allungata di una coccinella, molto meno di un bruco. E cambiamo domanda: «cimice?».</p>
<p>Le cimici stanno <strong>in mezzo</strong>, fra le coccinelle da una parte e i bruchi dall’altra: nessuna retta le lascia da sole su un lato. Due rette sì, una fascia: il problema non è linearmente separabile.</p>
<p>È la finestra della glicemia, in due dimensioni: lungo <span class="math inline">\(x_2 - x_1\)</span> vengono prima le coccinelle, poi le cimici, poi i bruchi.</p>
</div><div class="column" style="width:46%;">
<p><img data-src="images/coccinelle_cimici_bruchi.png"></p>
</div></div>
<aside class="notes">
<p>Misure inventate come nella slide prima (stesse coccinelle, stessi bruchi); l’ordine per allungamento è quello vero: una cimice è più allungata di una coccinella, molto meno di un bruco. «Nessuna retta» lo verifica lo script della figura: su 7200 direzioni le proiezioni delle cimici e degli altri insetti si sovrappongono sempre. La fascia <span class="math inline">\(|x_2 - x_1| &lt; 0.35\)</span> sono due neuroni con la stessa direzione e bias diversi, più un terzo che li combina: è la costruzione dello XOR con lo strato nascosto, dove le due rette parallele saranno l’OR e l’AND.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cosa-chiediamo-a-un-neurone" class="slide level2 smaller">
<h2>Cosa Chiediamo a un Neurone</h2>
<p>Un neurone deve prendere una <strong>decisione</strong>: uscita 1 (“sì”) o 0 (“no”). Il banco di prova classico è <strong>due ingressi binari</strong> <span class="math inline">\(A, B \in \{0,1\}\)</span> e una <strong>porta logica</strong> da realizzare.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(A\)</span></th>
<th style="text-align: center;"><span class="math inline">\(B\)</span></th>
<th style="text-align: center;">AND</th>
<th style="text-align: center;">OR</th>
<th style="text-align: center;">XOR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><strong>1</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<p>Lo <strong>XOR</strong> (<em>OR esclusivo</em>) vale 1 quando i due ingressi sono <strong>diversi</strong>.</p>
<p>Geometricamente ogni porta è un problema di <strong>classificazione</strong>: i quattro ingressi sono i vertici di un quadrato nel piano <span class="math inline">\((A, B)\)</span>, e la porta colora ogni vertice con la sua uscita. Il neurone deve separare i vertici “1” dagli “0” — vediamo se lo strumento basta.</p>
</section>
<section id="un-neurone-due-ingressi" class="slide level2 smaller">
<h2>Un neurone, due ingressi</h2>

<img data-src="images/neurone_due_ingressi.png" class="quarto-figure quarto-figure-center r-stretch"><p>È il percettrone di prima con <span class="math inline">\(n = 2\)</span> ingressi. Le tre porte sono tre richieste allo <strong>stesso</strong> neurone, e per soddisfarle si possono cambiare solo i tre numeri <span class="math inline">\(w_1, w_2, b\)</span>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">porta</th>
<th style="text-align: center;"><span class="math inline">\(w_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(w_2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(b\)</span></th>
<th style="text-align: left;">uscita 1 quando</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">AND</td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-1.5\)</span></td>
<td style="text-align: left;"><span class="math inline">\(A + B &gt; 1.5\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">OR</td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.5\)</span></td>
<td style="text-align: left;"><span class="math inline">\(A + B &gt; 0.5\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">XOR</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: left;">nessuna scelta funziona</td>
</tr>
</tbody>
</table>
</section>
<section id="and-e-or-la-retta-esiste" class="slide level2 smaller">
<h2>AND e OR: la retta esiste</h2>

<img data-src="images/and_or_separabili.png" class="quarto-figure quarto-figure-center r-stretch"><p>Con <span class="math inline">\(w_1 = w_2 = 1\)</span> il neurone guarda <strong>un numero solo</strong>, <span class="math inline">\(s = A + B\)</span>, come guardava solo la glicemia. Sotto, ogni vertice è segnato al suo valore di <span class="math inline">\(s\)</span>: AND e OR sono una soglia, come «diabete?». Lo XOR (non disegnato) su <span class="math inline">\(s\)</span> vale <span class="math inline">\(0, 1, 0\)</span>: una finestra, come «glicemia nella norma?».</p>
<aside class="notes">
<p>Se uno studente obietta che <span class="math inline">\(s = A + B\)</span> è solo UNA scelta di pesi: per lo XOR basta. Lo XOR è simmetrico in <span class="math inline">\(A \leftrightarrow B\)</span>, quindi se una terna <span class="math inline">\((w_1, w_2, b)\)</span> funzionasse funzionerebbe anche <span class="math inline">\((w_2, w_1, b)\)</span>. Le terne che funzionano sono un insieme convesso (intersezione di semispazi), quindi funzionerebbe anche la media, che ha <span class="math inline">\(w_1 = w_2\)</span> e guarda solo <span class="math inline">\(s\)</span>. Ma <span class="math inline">\(z = w\,s + b\)</span> è monotona in <span class="math inline">\(s\)</span>: non può essere spenta in 0, accesa in 1 e spenta in 2. Nessuna terna, quindi. È la conclusione delle note della slide dopo, per un’altra strada.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="il-problema-dello-xor" class="slide level2 smaller">
<h2>Il Problema dello XOR</h2>
<p>Per lo XOR i vertici da separare sono <strong>opposti</strong>: <span class="math inline">\((0,1)\)</span> e <span class="math inline">\((1,0)\)</span> contro <span class="math inline">\((0,0)\)</span> e <span class="math inline">\((1,1)\)</span>. Nessuna retta li divide. Nel 1969 Minsky e Papert lo dimostrarono, e la ricerca sulle reti neurali si fermò per anni. La cura è uno <strong>strato nascosto</strong>: due rette, cioè due neuroni, e una non-linearità fra i due strati. Perché uno strato nascosto basti — non solo per lo XOR, ma per <em>qualunque</em> funzione continua — lo dice il <strong>teorema di approssimazione universale</strong>, fra poche slide.</p>

<img data-src="images/xor_problem.png" class="quarto-figure quarto-figure-center r-stretch" style="width:66.0%"><aside class="notes">
<p>Dimostrazione in tre righe, se serve alla lavagna: con <span class="math inline">\(y = \Theta(w_1 A + w_2 B + b)\)</span>, dove <span class="math inline">\(\Theta(z) = 1\)</span> solo per <span class="math inline">\(z &gt; 0\)</span>, servono <span class="math inline">\(b \le 0\)</span> (per <span class="math inline">\(A=B=0\)</span>), <span class="math inline">\(w_1+w_2+b \le 0\)</span> (per <span class="math inline">\(A=B=1\)</span>), <span class="math inline">\(w_1+b &gt; 0\)</span> e <span class="math inline">\(w_2+b &gt; 0\)</span> (per i due casi misti). Sommando le ultime due: <span class="math inline">\(w_1+w_2+2b &gt; 0\)</span>; sottraendo la condizione per <span class="math inline">\(A=B=1\)</span>: <span class="math inline">\(b &gt; 0\)</span>. Contraddizione con la prima. Nessuna scelta di pesi funziona, e aggiungere uscite in parallelo non aiuta: ognuna vede lo stesso problema. Nel pannello di destra le due rette punteggiate, <span class="math inline">\(A+B=0.5\)</span> e <span class="math inline">\(A+B=1.5\)</span>, sono esattamente i due neuroni nascosti che risolvono il problema: il neurone d’uscita deve solo accendersi nella fascia fra le due.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="la-funzione-di-attivazione" class="slide level2 smaller">
<h2>La Funzione di Attivazione</h2>
<p>Per permettere al neurone di piegare, flettere e spezzare le rette, dobbiamo forzarlo ad attraversare una funzione matematica “Curva” o “Non-Lineare”.</p>
<p>Chiamiamo questa funzione <strong>Funzione di Attivazione</strong> <span class="math inline">\(f(z)\)</span>.</p>
<p>La formula del neurone diventa quindi:</p>
<p><span class="math display">\[ a = f(z) = f\left(\sum_{i=1}^{n} (w_i x_i) + b\right) \]</span></p>
<p>L’output finale è <span class="math inline">\(a\)</span> (Attivazione), ed è quello che verrà passato al livello successivo.</p>
</section>
<section id="piegare-lo-spazio" class="slide level2 smaller">
<h2>Piegare lo spazio</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Avviso</strong></p>
</div>
<div class="callout-content">
<p>IL SEGRETO DEL DEEP LEARNING</p>
</div>
</div>
</div>
<p>Se collegate tra loro 100 layer di neuroni puramente lineari (senza funzione di attivazione), per le leggi dell’algebra lineare l’intera gigantesca rete da milioni di parametri collassa in <strong>un solo layer lineare</strong>, cioè in una sola matrice (più un vettore di bias): il prodotto delle cento. È tempo sprecato.</p>
<p>Uno strato lineare è <span class="math inline">\(\mathbf{x} \mapsto \mathbf{W}\mathbf{x} + \mathbf{b}\)</span>, con una riga di <span class="math inline">\(\mathbf{W}\)</span> per neurone. Due strati:</p>
<p><span class="math display">\[ \mathbf{W}^{(2)}\left(\mathbf{W}^{(1)}\mathbf{x} + \mathbf{b}^{(1)}\right) + \mathbf{b}^{(2)} = \underbrace{\mathbf{W}^{(2)}\mathbf{W}^{(1)}}_{\mathbf{W}'}\,\mathbf{x} + \underbrace{\mathbf{W}^{(2)}\mathbf{b}^{(1)} + \mathbf{b}^{(2)}}_{\mathbf{b}'} \]</span></p>
<p>Solo una funzione di attivazione non lineare fra uno strato e l’altro impedisce il collasso: ogni strato <strong>deforma</strong> lo spazio degli ingressi, come un cambio di coordinate non lineare, finché basta un confine dritto.</p>
<aside class="notes">
<p>“Piegare” e non “curvare”: con la ReLU (fra poche slide) la rete è una funzione lineare a tratti, con curvatura nulla ovunque tranne lungo le pieghe, che stanno su iperpiani. Con la sigmoide la deformazione è liscia, ma il punto resta lo stesso: un cambio di coordinate non lineare dopo il quale basta un confine dritto. Non serve salire di dimensione: nello XOR lo strato nascosto ha due neuroni, quanti gli ingressi. Salire di dimensione è l’idea dei metodi a kernel, non il motivo per cui una rete funziona. La slide dopo lo fa vedere sullo XOR: i due neuroni nascosti mandano <span class="math inline">\((0,1)\)</span> e <span class="math inline">\((1,0)\)</span> nello stesso punto, e nel piano <span class="math inline">\((h_1, h_2)\)</span> una retta basta.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="lo-xor-con-uno-strato-nascosto" class="slide level2 smaller">
<h2>Lo XOR con uno strato nascosto</h2>

<img data-src="images/xor_rete.png" class="quarto-figure quarto-figure-center r-stretch"><p>È il neurone di «Un neurone, due ingressi», tre volte. Due copie leggono <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span>, regolate come l’OR e come l’AND: non sono né ingressi né uscita, e formano uno <strong>strato nascosto</strong>. La terza, <span class="math inline">\(y\)</span>, legge le loro uscite e calcola “<span class="math inline">\(h_1\)</span> e non <span class="math inline">\(h_2\)</span>”: lo XOR.</p>
<p>La non-linearità sta nei riquadri <span class="math inline">\(z &gt; 0\)</span> dei neuroni nascosti. Toglieteli, e <span class="math inline">\(y\)</span> riceverebbe <span class="math inline">\((A+B-0.5)-(A+B-1.5)\)</span>: il suo <span class="math inline">\(z\)</span> varrebbe <span class="math inline">\(0.5\)</span> per qualunque ingresso.</p>
<aside class="notes">
<p>Sono le due rette della slide dello XOR più un neurone d’uscita, con la regola <span class="math inline">\(z &gt; 0\)</span> di sempre. Il riquadro <span class="math inline">\(z &gt; 0\)</span> è la step function della slide dopo: qui fa da funzione di attivazione. Pesi e bias di <span class="math inline">\(h_1\)</span> e <span class="math inline">\(h_2\)</span> sono le righe OR e AND della tabella di «Un neurone, due ingressi». La non-linearità che serve è la decisione <span class="math inline">\(z &gt; 0\)</span> dei neuroni nascosti: senza, <span class="math inline">\(h_1\)</span> e <span class="math inline">\(h_2\)</span> sarebbero lineari in <span class="math inline">\(A, B\)</span>, e per «Piegare lo spazio» tutto collasserebbe in una retta sola.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cosa-vede-il-neurone-duscita" class="slide level2 smaller">
<h2>Cosa vede il neurone d’uscita</h2>

<img data-src="images/xor_strato_nascosto.png" class="quarto-figure quarto-figure-center r-stretch"><p>A destra ogni ingresso è disegnato nel punto <span class="math inline">\((h_1, h_2)\)</span>, cioè (OR, AND), in cui lo porta lo strato nascosto. <span class="math inline">\((0,1)\)</span> e <span class="math inline">\((1,0)\)</span> finiscono nello stesso punto, e il vertice <span class="math inline">\(h_1 = 0,\ h_2 = 1\)</span> resta vuoto, perché AND senza OR è impossibile. Al neurone <span class="math inline">\(y\)</span> restano tre punti, e una retta li separa.</p>
<aside class="notes">
<p>Il punto è che i due “sì” dello XOR cadono nello <strong>stesso</strong> punto dello strato nascosto: se finissero su due vertici opposti saremmo di nuovo allo XOR. Il vertice vuoto è la conseguenza (AND vero e OR falso non capita mai), e il neurone <span class="math inline">\(y\)</span> non deve classificarlo.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="la-step-function-obsoleta" class="slide level2 smaller">
<h2>La Step Function (Obsoleta)</h2>
<p>Quale funzione <span class="math inline">\(f(z)\)</span> usare?</p>
<p>Negli anni ’60 usavano la <strong>Step Function</strong> (Funzione a Gradino). - Se <span class="math inline">\(z &gt; 0\)</span>, l’output è <span class="math inline">\(1\)</span> (Neurone Acceso). - Se <span class="math inline">\(z \le 0\)</span>, l’output è <span class="math inline">\(0\)</span> (Neurone Spento).</p>
<p>È concettualmente semplice (come un interruttore), ma ha un difetto mortale: è completamente <strong>Piatta</strong> ovunque, tranne nel punto zero. Il Machine Learning si basa sul calcolo delle <em>Derivate</em> per correggere gli errori. La derivata di una linea piatta è ZERO. Il neurone non impara nulla.</p>
</section>
<section id="la-funzione-sigmoide" class="slide level2 smaller">
<h2>La Funzione Sigmoide</h2>
<p>Per decenni, la regina incontrastata è stata la <strong>Sigmoide</strong>. Una bellissima funzione a forma di “S” morbida.</p>
<p><span class="math display">\[ f(z) = \frac{1}{1 + e^{-z}} \]</span></p>
<p><strong>Vantaggi:</strong> 1. Schiaccia tutto l’universo infinito dei numeri tra <span class="math inline">\(0\)</span> e <span class="math inline">\(1\)</span>. Perfetta per esprimere Probabilità (“La probabilità che questa foto sia un Gatto è 0.98”). 2. È derivabile ovunque in modo dolce.</p>
<p><strong>Svantaggio:</strong> Se il numero in input è molto alto o molto basso, la curva si “appiattisce”. Il gradiente sparisce (Vanishing Gradient), bloccando l’apprendimento.</p>
</section>
<section id="lera-del-deep-learning-relu" class="slide level2 smaller">
<h2>L’Era del Deep Learning: ReLU</h2>
<p>Oggi la grande maggioranza delle reti neurali usa una funzione apparentemente banale: la <strong>ReLU</strong> (Rectified Linear Unit).</p>
<p><span class="math display">\[ f(z) = \max(0, z) \]</span></p>
<ul>
<li>Se il numero è negativo, esce Zero.</li>
<li>Se il numero è positivo, esce il numero stesso.</li>
</ul>
<p>Sembra stupida, vero? Come fa a essere “Non-Lineare”? Il trucco è nello “spigolo” allo zero.</p>
</section>
<section id="perché-relu-funziona" class="slide level2 smaller">
<h2>Perché ReLU funziona?</h2>
<p>La ReLU è non-lineare grazie al suo taglio brutale sotto lo zero. Ma il suo vero superpotere è che per tutti i numeri positivi, la sua pendenza (derivata) è costante e vale 1.</p>
<p>Il segnale non si spegne mai. Il gradiente fluisce perfetto attraverso centinaia di layer senza mai svanire. È la funzione che ha permesso alle reti di diventare “Deep” (Profonde).</p>
<p>Inoltre <span class="math inline">\(\max(0, x)\)</span> è un confronto: <strong>un ciclo di clock</strong>. Un esponenziale <span class="math inline">\(e^{-x}\)</span> ne costa alcune decine. Su miliardi di attivazioni la differenza si sente.</p>
</section>
<section id="confronto-step-vs-sigmoid-vs-relu" class="slide level2">
<h2>Confronto: Step vs Sigmoid vs ReLU</h2>

<img data-src="images/activation_functions.png" class="quarto-figure quarto-figure-center r-stretch" style="width:95.0%"></section>
<section id="una-rete-di-neuroni-il-multi-layer-perceptron" class="slide level2 smaller">
<h2>Una rete di neuroni: il Multi-Layer Perceptron</h2>
<p>Ora che il neurone ha una funzione di attivazione non lineare, ne prendiamo tanti e li organizziamo in strati (layer).</p>
<p>Nasce il <strong>Multi-Layer Perceptron (MLP)</strong> o Rete <em>Feedforward Fully Connected</em>.</p>
<ul>
<li><strong>Input Layer:</strong> I dati puri (es. i pixel dell’immagine).</li>
<li><strong>Hidden Layers:</strong> I livelli intermedi “nascosti”. Ogni neurone è connesso a <em>tutti</em> i neuroni del layer precedente.</li>
<li><strong>Output Layer:</strong> La risposta finale (es. 10 neuroni per le 10 cifre da 0 a 9).</li>
</ul>
<p>Lo XOR con uno strato nascosto era già un MLP: 2 ingressi, 2 neuroni nascosti, 1 uscita.</p>
<aside class="notes">
<p>Il nome è storico: i neuroni di un MLP non sono percettroni con il gradino, hanno attivazioni derivabili (sigmoide, ReLU), altrimenti la rete non si potrebbe addestrare (slide della step function). Con neuroni a soglia, due nascosti sono il minimo per lo XOR in una rete a strati: con uno solo l’uscita dipende da una sola soglia su <span class="math inline">\(A, B\)</span> e resta lineare.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="architettura-di-base" class="slide level2 smaller">
<h2>Architettura di Base</h2>
<p>Ecco la rappresentazione visiva dei flussi (Edges) in un MLP.</p>

<img data-src="images/mlp_schema.png" class="quarto-figure quarto-figure-center r-stretch"><p>Il groviglio di frecce è letteralmente l’insieme dei Pesi (Weights) della rete. Un livello denso si chiama Fully Connected perché non manca nemmeno una freccia.</p>
<aside class="notes">
<p>Figura ridisegnata e semplificata da T. Rashid, Make Your Own Neural Network, p.&nbsp;58. Gli ingressi sono quadrati: sono i dati e non calcolano niente. Nel libro anche il primo strato è disegnato con i “neurons”.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="la-nostra-architettura-mnist" class="slide level2 smaller">
<h2>La Nostra Architettura: MNIST</h2>
<p>Per MNIST: <strong>784 → 200 → 10</strong>, un solo strato nascosto, sigmoide su entrambi. Ingressi in <span class="math inline">\([0.01,\,0.99]\)</span>, la cifra è il neurone più acceso. Basta a superare il 90%; ReLU e softmax sono varianti da progetto.</p>

<img data-src="images/nn_architecture.png" class="quarto-figure quarto-figure-center r-stretch" style="width:76.0%"></section>
<section id="forward-propagation-strato-dopo-strato" class="slide level2 smaller">
<h2>Forward Propagation: strato dopo strato</h2>
<p>Il processo con cui i dati entrano dall’Input Layer, vengono moltiplicati per i pesi, sommati, passati nelle funzioni di attivazione livello dopo livello fino ad uscire come risultato finale, si chiama <strong>Forward Propagation</strong>.</p>
<p>Il calcolo va solo in avanti, dall’ingresso all’uscita, senza mai tornare indietro (Feed-forward).</p>
<p>La domanda sorge spontanea: <em>Costruire una rete del genere serve davvero a qualcosa o è solo un esercizio di stile informatico?</em></p>
</section>
<section id="vettori-in-ingresso-vettori-in-uscita" class="slide level2 smaller">
<h2>Vettori in ingresso, vettori in uscita</h2>
<p>Prima di tornare alle reti, un cambio di prospettiva che vale per tutto il corso.</p>
<p>Un’immagine MNIST è <span class="math inline">\(28\times 28\)</span> pixel: <strong>784 numeri</strong>, un vettore <span class="math inline">\(\mathbf{x}\in\mathbb{R}^{784}\)</span>. Un suono è una sequenza di campioni. Un testo diventa numeri (codici, o <em>embedding</em>). Un video è una pila di immagini. Qualunque oggetto, una volta digitalizzato, <strong>è un vettore</strong>.</p>
<p>E allora <em>classificare</em> — “questa immagine è un 7” — non è altro che una <strong>funzione</strong> <span class="math inline">\(f:\mathbb{R}^{784}\to\mathbb{R}^{10}\)</span>, che al vettore dei pixel associa le dieci uscite, una per cifra. Tradurre una frase, prevedere la parola successiva, diagnosticare da una radiografia: sempre una funzione che manda vettori in vettori. “Ragionare”, in questo senso, è calcolare <span class="math inline">\(f\)</span>.</p>
<p>Le domande diventano due, e la seconda è tutto il corso:</p>
<ol type="1">
<li><strong>Esiste</strong> una rete neurale che calcola <span class="math inline">\(f\)</span>?</li>
<li>Come si <strong>trovano</strong> i suoi pesi?</li>
</ol>
</section>
<section id="il-teorema-di-approssimazione-universale" class="slide level2 smaller">
<h2>Il Teorema di Approssimazione Universale</h2>
<p>Alla prima domanda risponde uno dei teoremi più belli della matematica applicata (Cybenko 1989; Hornik 1991; Leshno et al.&nbsp;1993).</p>
<blockquote>
<p><strong>Teorema.</strong> Sia <span class="math inline">\(f:K\to\mathbb{R}^M\)</span> continua su un compatto <span class="math inline">\(K\subset\mathbb{R}^N\)</span>, e sia <span class="math inline">\(\varphi\)</span> continua e <strong>non polinomiale</strong> (sigmoide, tanh, ReLU…). Per ogni <span class="math inline">\(\varepsilon&gt;0\)</span> esistono un numero <span class="math inline">\(H\)</span> di neuroni nascosti e pesi <span class="math inline">\(\mathbf{W}^{(1)}, \mathbf{b}^{(1)}, \mathbf{W}^{(2)}\)</span> tali che <span class="math display">\[ F(\mathbf{x}) = \mathbf{W}^{(2)}\,\varphi\!\left(\mathbf{W}^{(1)}\mathbf{x}+\mathbf{b}^{(1)}\right), \qquad \max_{\mathbf{x}\in K}\|F(\mathbf{x})-f(\mathbf{x})\| &lt; \varepsilon . \]</span></p>
</blockquote>
<p>Cioè: <strong>un solo strato nascosto</strong>, abbastanza largo, approssima qualunque funzione continua con la precisione che si vuole.</p>
</section>
<section id="lipotesi-che-conta-la-non-linearità" class="slide level2 smaller">
<h2>L’Ipotesi che Conta: la Non-Linearità</h2>
<p>Nel teorema c’è un’ipotesi che non si può togliere: <span class="math inline">\(\varphi\)</span> <strong>non polinomiale</strong>, in particolare non lineare.</p>
<p>Provate a toglierla. Se <span class="math inline">\(\varphi\)</span> fosse lineare, <span class="math inline">\(\varphi(\mathbf{z}) = \mathbf{z}\)</span>, la rete a due strati sarebbe</p>
<p><span class="math display">\[ F(\mathbf{x}) = \mathbf{W}^{(2)}\left(\mathbf{W}^{(1)}\mathbf{x} + \mathbf{b}^{(1)}\right) = \underbrace{\mathbf{W}^{(2)}\mathbf{W}^{(1)}}_{\text{una sola matrice}}\,\mathbf{x} + \mathbf{W}^{(2)}\mathbf{b}^{(1)} , \]</span></p>
<p>cioè <strong>un percettrone a singolo strato</strong>: la composizione di due mappe lineari è lineare, e con mille strati lineari si otterrebbe sempre e solo una matrice. Saremmo di nuovo fermi allo XOR.</p>
<p>È la non-linearità fra gli strati a dare alla composizione più potere dei suoi pezzi: per questo nel Lab 07 ogni strato lineare (nel vostro framework, un <code>DenseLayer</code>) sarà seguito da uno strato di attivazione. Le <span class="math inline">\(\varphi\)</span> viste poche slide fa non erano un dettaglio: erano la condizione perché tutto questo funzioni.</p>
</section>
<section id="cosa-il-teorema-non-dice" class="slide level2 smaller">
<h2>Cosa il Teorema Non Dice</h2>
<p>In pratica: se il compito si può scrivere come una funzione continua su un dominio limitato — riconoscere una voce, guidare un’auto, leggere una radiografia — <strong>esiste</strong> una configurazione di pesi che la approssima con la precisione voluta.</p>
<p>Ma il teorema è di <strong>esistenza</strong>, non di costruzione, e tace su tre cose:</p>
<ul>
<li><strong>quanti</strong> neuroni nascosti servono: <span class="math inline">\(H\)</span> può essere enorme, e in pratica conviene <em>più strati</em> stretti che uno solo larghissimo (è il “deep” di Deep Learning);</li>
<li><strong>come trovare</strong> i pesi: il teorema non dà nessun algoritmo. Questo è il lavoro della <strong>Backpropagation</strong>, la prossima lezione;</li>
<li><strong>come si comporta</strong> la rete sui dati che non ha visto: approssimare <span class="math inline">\(f\)</span> sui dati di addestramento non garantisce nulla altrove. È il problema della <em>generalizzazione</em>: nel Lab 14 misurerete la performance su un <em>test set</em> separato, e nel Lab 15, addestrando su pochi esempi, vedrete la rete fare il 99% su quelli visti e l’85% sugli altri (overfitting).</li>
</ul>
</section>
<section id="il-problema-computazionale-i-cicli-for" class="slide level2 smaller">
<h2>Il Problema Computazionale (I Cicli For)</h2>
<p>Fermiamoci un momento e pensiamo come un programmatore al primo anno di Informatica scriverebbe la <em>Forward Propagation</em>.</p>
<p>Per ogni neurone <span class="math inline">\(i\)</span> del layer <span class="math inline">\(L\)</span> dovrebbe calcolare <span class="math inline">\(z_i = \sum_j w_{ij}\,x_j + b_i\)</span>, dove gli <span class="math inline">\(x_j\)</span> sono le uscite del layer <span class="math inline">\(L-1\)</span>. In C++, scriverebbe:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb1-1"><a aria-label="1"></a><span class="co">// Vogliamo calcolare le attivazioni del Layer L</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="cf">for</span> <span class="op">(</span><span class="dt">int</span> i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> num_neuroni_layer_L<span class="op">;</span> i<span class="op">++)</span> <span class="op">{</span></span>
<span id="cb1-3"><a aria-label="3"></a>    <span class="dt">double</span> z <span class="op">=</span> bias<span class="op">[</span>i<span class="op">];</span></span>
<span id="cb1-4"><a aria-label="4"></a>    <span class="cf">for</span> <span class="op">(</span><span class="dt">int</span> j <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> j <span class="op">&lt;</span> num_neuroni_layer_L_meno_1<span class="op">;</span> j<span class="op">++)</span> <span class="op">{</span></span>
<span id="cb1-5"><a aria-label="5"></a>        z <span class="op">+=</span> peso<span class="op">[</span>i<span class="op">][</span>j<span class="op">]</span> <span class="op">*</span> input<span class="op">[</span>j<span class="op">];</span></span>
<span id="cb1-6"><a aria-label="6"></a>    <span class="op">}</span></span>
<span id="cb1-7"><a aria-label="7"></a>    attivazione<span class="op">[</span>i<span class="op">]</span> <span class="op">=</span> relu<span class="op">(</span>z<span class="op">);</span></span>
<span id="cb1-8"><a aria-label="8"></a><span class="op">}</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>Vi sembra un buon codice?</p>
</section>
<section id="il-codice-naif-lento-e-mortale" class="slide level2 smaller">
<h2>Il Codice Naif (Lento e Mortale)</h2>
<p>Se fate così, <strong>fallirete</strong>. Una rete vera (es. GPT o ResNet) ha <em>migliaia</em> di neuroni per layer.</p>
<p>Un layer da 4000 neuroni connesso a un layer da 4000 neuroni significa: <span class="math inline">\(4000 \times 4000 = 16.000.000\)</span> di moltiplicazioni all’interno di un doppio ciclo <code>for</code>. Immaginate di ripeterlo per 100 layer.</p>
<p>I cicli <code>for</code> in C++ sono puramente SEQUENZIALI. Il processore fa la prima moltiplicazione, aspetta che finisca, fa la seconda, aspetta, fa la terza. E l’addestramento ripete questo calcolo su ogni esempio, più e più volte: ci vuole moltissimo tempo.</p>
</section>
<section id="lalgebra-lineare-in-soccorso" class="slide level2 smaller">
<h2>L’Algebra Lineare in Soccorso</h2>
<p>Per abbattere i tempi di calcolo, la matematica ci offre una scappatoia monumentale: smettere di guardare ai neuroni come singole entità, e guardarli come <strong>Vettori e Matrici</strong>.</p>
<p>Invece di calcolare l’output del “Neurone 1” e poi del “Neurone 2”, calcoleremo l’output <strong>di tutto il Layer contemporaneamente</strong>.</p>
<p>Questo processo di astrazione matematica si chiama <strong>Vettorizzazione</strong>.</p>
</section>
<section id="la-vettorizzazione-concetto" class="slide level2 smaller">
<h2>La Vettorizzazione (Concetto)</h2>
<p>Immaginate che il Layer precedente abbia emesso tre output (attivazioni). Li impiliamo in un Vettore Colonna (una matrice di dimensione <span class="math inline">\(3 \times 1\)</span>) che chiameremo <span class="math inline">\(\mathbf{x}\)</span>.</p>
<p><span class="math display">\[
\mathbf{x} = \begin{bmatrix} 1.2 \\ -0.5 \\ 0.8 \end{bmatrix}
\]</span></p>
<p>Immaginiamo che il nostro Layer attuale abbia 2 neuroni, e che ognuno abbia il suo Bias. Li mettiamo nel Vettore Colonna <span class="math inline">\(\mathbf{b}\)</span> (dimensione <span class="math inline">\(2 \times 1\)</span>).</p>
<p><span class="math display">\[
\mathbf{b} = \begin{bmatrix} 0.1 \\ -0.2 \end{bmatrix}
\]</span></p>
</section>
<section id="lo-schema-della-rete" class="slide level2 smaller">
<h2>Lo Schema della Rete</h2>

<img data-src="images/mlp_scheme.png" class="quarto-figure quarto-figure-center r-stretch" style="width:78.0%"><p>Lo stesso esempio di prima — tre ingressi, due neuroni — visto come circuito: <strong>sei pesi</strong>, uno per freccia. <span class="math inline">\(\omega_{i,j}\)</span> collega il nodo <span class="math inline">\(i\)</span> del layer #1 al nodo <span class="math inline">\(j\)</span> del layer #2: <strong>primo indice la partenza, secondo l’arrivo</strong>, come nel libro di Rashid. E appartengono al <strong>layer #2</strong>, quello che li riceve: nel codice sarà così anche per <code>DenseLayer</code>.</p>
</section>
<section id="la-matrice-dei-pesi-w" class="slide level2 smaller">
<h2>La Matrice dei Pesi (W)</h2>
<p>Ora il pezzo grosso: I Pesi. Ogni neurone del nostro layer ha 3 frecce in entrata (provenienti da <span class="math inline">\(\mathbf{x}\)</span>). Dato che abbiamo 2 neuroni, in totale ci sono 6 pesi.</p>
<p>Li organizziamo in una formidabile Matrice bidimensionale <span class="math inline">\(\mathbf{W}\)</span> (dimensione <span class="math inline">\(2 \times 3\)</span>).</p>
<p><span class="math display">\[
\mathbf{W} = \begin{bmatrix}
w_{11} &amp; w_{12} &amp; w_{13} \\
w_{21} &amp; w_{22} &amp; w_{23}
\end{bmatrix}
\]</span> Ogni <em>riga</em> di questa matrice rappresenta tutti i pesi appartenenti a un singolo neurone del nostro strato: <span class="math inline">\(w_{jk}\)</span> è il peso con cui il neurone <span class="math inline">\(j\)</span> legge l’ingresso <span class="math inline">\(k\)</span>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Attenzione all’ordine degli indici. Nello schema di prima (e nel libro di Rashid) <span class="math inline">\(\omega_{i,j}\)</span> va <strong>dalla</strong> partenza <span class="math inline">\(i\)</span> <strong>all’</strong>arrivo <span class="math inline">\(j\)</span>; qui invece la <strong>riga</strong> è il neurone d’arrivo, quindi questa <span class="math inline">\(\mathbf{W}\)</span> è la <strong>trasposta</strong> di quella tabella. È lei che serve per moltiplicare, ed è per questo che nel codice si chiamerà <code>Wt</code>.</p>
</div>
</div>
</div>
</section>
<section id="lequazione-sacra-del-machine-learning" class="slide level2 smaller">
<h2>L’Equazione Sacra del Machine Learning</h2>
<p>Unendo i pezzi con le spietate leggi della Moltiplicazione tra Matrici (Riga per Colonna), i doppi cicli <code>for</code> spariscono nel nulla, sostituiti da una singola, elegante equazione:</p>
<p><span class="math display">\[ \mathbf{z} = \mathbf{W} \cdot \mathbf{x} + \mathbf{b} \]</span></p>
<p>Questa equazione produce un Vettore Colonna <span class="math inline">\(\mathbf{z}\)</span> di dimensione <span class="math inline">\(2 \times 1\)</span>, contenente simultaneamente lo stato di eccitazione dei nostri 2 neuroni!</p>
<p><span class="math display">\[
\begin{bmatrix} z_1 \\ z_2 \end{bmatrix} =
\begin{bmatrix}
w_{11} &amp; w_{12} &amp; w_{13} \\
w_{21} &amp; w_{22} &amp; w_{23}
\end{bmatrix}
\cdot
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}
+
\begin{bmatrix} b_1 \\ b_2 \end{bmatrix}
\]</span></p>
</section>
<section id="il-vantaggio-hardware-simd-gpu" class="slide level2 smaller">
<h2>Il Vantaggio Hardware (SIMD &amp; GPU)</h2>
<p>Perché scrivere <span class="math inline">\(\mathbf{W} \cdot \mathbf{x}\)</span> è infinitamente più veloce dei cicli <code>for</code>?</p>
<p>Perché la moltiplicazione Riga <span class="math inline">\(\times\)</span> Colonna è un’operazione brutalmente <strong>Parallela</strong>. Il calcolo del Neurone 1 non dipende minimamente dal calcolo del Neurone 2.</p>
<p>I processori Intel moderni posseggono istruzioni speciali (SIMD - <em>Single Instruction Multiple Data</em>) che eseguono 8 moltiplicazioni contemporaneamente nello stesso nanosecondo. Le <strong>GPU</strong> (Schede Video Nvidia) ne posseggono migliaia, processando enormi matrici istantaneamente.</p>
</section>
<section id="c-e-librerie-ottimizzate-eigen-blas" class="slide level2 smaller">
<h2>C++ e Librerie Ottimizzate (Eigen / BLAS)</h2>
<p>In C++, non dovrete (e non dovreste mai) scrivervi a mano la moltiplicazione tra matrici.</p>
<p>Nel vostro progetto, userete una libreria di algebra lineare di livello industriale come <strong>Eigen</strong> (o BLAS/LAPACK). Basterà definire due oggetti <code>Eigen::Matrix</code> e moltiplicarli con il banale operatore <code>*</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb2-1"><a aria-label="1"></a><span class="co">// Eigen usa istruzioni Assembly SIMD sotto il cofano!</span></span>
<span id="cb2-2"><a aria-label="2"></a>Eigen<span class="op">::</span>VectorXd z <span class="op">=</span> W <span class="op">*</span> x <span class="op">+</span> b<span class="op">;</span> </span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>Il vostro codice risulterà 100 volte più pulito da leggere e 1000 volte più veloce in esecuzione.</p>
</section>
<section id="lequazione-ricorsiva-finale" class="slide level2 smaller">
<h2>L’Equazione Ricorsiva Finale</h2>
<p>L’ultimo passo per ottenere i valori da inviare al livello successivo è applicare la funzione di attivazione a tutto il Vettore Colonna.</p>
<p><span class="math display">\[ \mathbf{a}^{(L)} = f\left( \mathbf{W}^{(L)} \mathbf{a}^{(L-1)} + \mathbf{b}^{(L)} \right) \]</span></p>
<p>Questa equazione racchiude l’intera logica di inferenza (Forward Pass) del Deep Learning moderno.</p>
<ul>
<li>Prendi l’input (<span class="math inline">\(\mathbf{a}^{(L-1)}\)</span>), moltiplica per i pesi (<span class="math inline">\(\mathbf{W}\)</span>), somma il bias (<span class="math inline">\(\mathbf{b}\)</span>).</li>
<li>Schiaccia con la funzione di attivazione (<span class="math inline">\(f\)</span> — per noi la sigmoide).</li>
<li>Invia al prossimo layer, e ripeti.</li>
</ul>
</section>
<section id="esercizio-in-classe-15-min-la-rete-a-mano" class="slide level2 smaller">
<h2>Esercizio in Classe (15 min): la rete a mano</h2>
<p>Niente computer: <strong>carta, penna, e il telefono per l’esponenziale.</strong> Una rete a tre ingressi e tre nodi:</p>
<p><span class="math display">\[\mathbf{W} = \begin{pmatrix} 0.9 &amp; 0.3 &amp; 0.4 \\ 0.2 &amp; 0.8 &amp; 0.2 \\ 0.1 &amp; 0.5 &amp; 0.6\end{pmatrix}
\qquad
\mathbf{x} = \begin{pmatrix} 0.9 \\ 0.1 \\ 0.8 \end{pmatrix}\]</span></p>
<ol type="1">
<li>Calcolate <span class="math inline">\(\mathbf{z} = \mathbf{W}\mathbf{x}\)</span> a mano.</li>
<li>Applicate la sigmoide a ciascuna componente: <span class="math inline">\(\sigma(z) = 1/(1+e^{-z})\)</span>.</li>
<li><strong>Contate quante moltiplicazioni avete fatto.</strong> Poi rifate il conto per la rete di MNIST, <span class="math inline">\(784 \to 200 \to 10\)</span>, e per un’epoca su 60.000 immagini.</li>
</ol>
<p>I numeri sono quelli dell’esempio svolto nel libro di Rashid: chi ce l’ha puo’ confrontare.</p>
</section>
<section id="esercizio-soluzione" class="slide level2 smaller">
<h2>Esercizio: Soluzione</h2>
<p><span class="math display">\[z_1 = 0.9\cdot0.9 + 0.3\cdot0.1 + 0.4\cdot0.8 = 1.16\]</span> <span class="math display">\[z_2 = 0.2\cdot0.9 + 0.8\cdot0.1 + 0.2\cdot0.8 = 0.42\]</span> <span class="math display">\[z_3 = 0.1\cdot0.9 + 0.5\cdot0.1 + 0.6\cdot0.8 = 0.62\]</span></p>
<p><span class="math display">\[\sigma(\mathbf{z}) = (0.761,\; 0.603,\; 0.650)\]</span></p>
</section>
<section id="e-il-conto-che-conta" class="slide level2 smaller">
<h2>E il conto che conta</h2>
<p>E il conto che conta davvero:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>rete</th>
<th>moltiplicazioni</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>la nostra <span class="math inline">\(3\times3\)</span></td>
<td>9</td>
</tr>
<tr class="even">
<td>MNIST, primo strato <span class="math inline">\(784\to200\)</span></td>
<td>156.800</td>
</tr>
<tr class="odd">
<td>secondo strato <span class="math inline">\(200\to10\)</span></td>
<td>2.000</td>
</tr>
<tr class="even">
<td><strong>una sola immagine</strong></td>
<td><strong>158.800</strong></td>
</tr>
<tr class="odd">
<td>un’epoca su 60.000 immagini</td>
<td><span class="math inline">\(9{,}5\cdot10^9\)</span></td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Nove moltiplicazioni le avete fatte a mano in un minuto. Nove <strong>miliardi</strong> sono un’epoca, e le epoche sono decine. Ecco perche’ il ciclo <code>for</code> ingenuo non basta, e perche’ la prossima volta parleremo di come si scrive quel prodotto in una riga sola.</p>
</div>
</div>
</div>
</section>
<section id="quesiti-finali" class="slide level2 smaller">
<h2>Quesiti finali</h2>
<p><strong>1. Dieci strati per niente.</strong> Immaginate una rete di dieci strati densi, ciascuno con la sua matrice di pesi, e <strong>nessuna</strong> funzione di attivazione fra uno e l’altro. Quanti strati servono per calcolare esattamente la stessa funzione?</p>
<p><strong>2. (aperta) Perchè “deep” e non “wide”?</strong> Il teorema di approssimazione universale dice che <strong>uno</strong> strato nascosto basta per qualunque funzione. E allora perchè il campo si chiama <em>deep</em> learning? Provate a rendere quantitativo l’argomento della slide “Cosa il Teorema Non Dice”: confrontate <strong>784 → 200 → 10</strong> con <strong>784 → 100 → 100 → 10</strong>, contate i pesi dell’una e dell’altra, e chiedetevi quante “pieghe” sa fare ciascuna.</p>
</section>
<section id="quesiti-finali-le-risposte" class="slide level2 smaller">
<h2>Quesiti finali: le risposte</h2>
<p><strong>1.</strong> Uno. <span class="math inline">\(\mathbf{W}_{10}(\mathbf{W}_9(\cdots \mathbf{W}_1 \mathbf{x})) =
(\mathbf{W}_{10} \cdots \mathbf{W}_1)\,\mathbf{x} = \mathbf{W}\mathbf{x}\)</span>: il prodotto di dieci matrici è una matrice. Dieci strati lineari non sono più espressivi di uno — sono lo stesso identico modello, scritto peggio e calcolato dieci volte più lentamente. La non-linearità non è un abbellimento: senza, la profondità non esiste proprio.</p>
<p><strong>2.</strong> Traccia: <span class="math inline">\(784 \times 200 + 200 \times 10 = 158.800\)</span> pesi contro <span class="math inline">\(784 \times 100 + 100 \times 100 + 100 \times 10 = 89.400\)</span>. La rete profonda costa poco più della <strong>metà</strong> ed è quella che in pratica funziona meglio: ogni strato ripiega lo spazio già ripiegato dal precedente, e le regioni che sa distinguere crescono come un prodotto, non come una somma. Il teorema garantisce che la rete larga <em>esiste</em>; non dice che sia quella conveniente, né che la troviate.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../images/logo_sapienza.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="../index.html">🏠 Torna alla Home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true,"storage":"lavagna-lezione-02"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'convex',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: '../mathjax/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiato!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiato!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            // Attach click handler to the DT
            const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
            for (const annoteDlNode of annoteDls) {
              annoteDlNode.addEventListener('click', (event) => {
                const clickedEl = event.target;
                if (clickedEl !== selectedAnnoteEl) {
                  unselectCodeLines();
                  const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
                  if (activeEl) {
                    activeEl.classList.remove('code-annotation-active');
                  }
                  selectCodeLines(clickedEl);
                  clickedEl.classList.add('code-annotation-active');
                } else {
                  // Unselect the line
                  unselectCodeLines();
                  clickedEl.classList.remove('code-annotation-active');
                }
              });
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>